name: Deployment

on:
  push:
    branches:
      - master

env:
  # The below options are required until the following issue is resolved
  # https://github.com/actions/checkout/issues/13
  GIT_AUTHOR_NAME: stack-test
  GIT_AUTHOR_EMAIL: example@example.com
  GIT_COMMITTER_NAME: stack-test
  GIT_COMMITTER_EMAIL: example@example.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.15
        uses: actions/setup-node@v2
        with:
          node-version: 14.15
      - name: Push to NPM
        run: |
          npm version "v1.0.${GITHUB_RUN_NUMBER}"
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Ping Discord on failure
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{ secrets.WEBHOOK_URL_MERGE_FAILURE }}
          details: "eslint-config-outstem merge workflow failed!"